### ISSUE TITLE
parsing result of (pactl list sink-inputs) fails on different locale

### ISSUE THREAD

**Issue by tmvkrpxl0** [siddhpant/broo#14]
pactl supports multiple locale and command $(pactl list sink-inputs) doesn't start with `Sink Input` on different locale
https://github.com/siddhpant/broo/blob/968db04106acf95f7176f156d3cf1867b3800f1c/broo#L97C39-L97C39
I suggest you to change it to $(LC_ALL=C pactl list sink-inputs)

**Comment by siddhpant** [comment]
Thanks!

Instead of that, we should just do `export LC_ALL=C.UTF-8` at the top.

Do you want to make a PR, or should I commit it?

**Comment by tmvkrpxl0** [comment]
Eh it's one line thing so doing it yourself will be simpler

**Comment by siddhpant** [comment]
sure.
