### ISSUE TITLE
broo does not start Flatpak Mumble for configuration step.

### ISSUE THREAD

**Issue by rockyamethyst** [siddhpant/broo#19]
When reaching the "Gotta configure the Mumble client from GUI for that sweet low latency." stage, upon pressing any button, Broo will just close finish the script after a few seconds, with no resulting mumble window (Even if there's no Flatpak Mumble installation present!). 

## Software Information:
- **OS:**                                  Fedora Linux 39 Bazzite (A Silverblue custom image)
- **Windowing System:**                          Wayland
- **Kernel Version:**                       Linux 6.5.9-300.fc39.x86_64
- **Pipewire Version:**                        PipeWire 0.3.84
- **broo Version:**                       Latest version on git

[Gravação de tela de 2023-11-11 11-10-58.webm](https://github.com/siddhpant/broo/assets/52428793/b48c4914-eec3-4bf4-8504-07043ed6e97c)

**Comment by siddhpant** [comment]
Well, you didn't install all dependencies :-P

The script is set to exit on failure. Unfortunately, the line where failure happens in this case has its output discarded.

Will add a check first to see if mumble really is there.

Also, flatpak wasn't tested, I will remove it. I assumed it will work the same but it doesn't. In fact, I cannot seem to find a way to run server from flatpak.

**Comment by rockyamethyst** [comment]
Taking a look at the [flatpak building repo](https://github.com/flathub/info.mumble.Mumble), seems like they just download only the client's source tarball, so no server functionality there *at all*.

Seems like the only way to use this is to layer a package, or compile from source, sadly. Maybe you could replace the bit talking about it being on Flathub with something along the lines of "The Flatpak version of Mumble only functions as a client, not a server."

Thank you for taking a look at this.

**Comment by siddhpant** [comment]
Yes, thank you for looking at it too!

Though I still need to add the check.
