### ISSUE TITLE
Failure: No such entity

### ISSUE THREAD

**Issue by CodeShakingSheep** [siddhpant/broo#23]
After I start broo there Mumble opens and I connect to the server. However, shortly after that the broo command exits with this message `Failure: No such entity`. Mumble still stays open.

I explicitly need to terminate broo with `broo -c` which then closes Mumble before I can start it again. Do you have any idea what's the issue here?

Edit: Additional info
I'm using Pulseaudio and the problem seems to appear in `add_mic_pulseaudio()`. Interestingly, I can see Broo as output device.
![image](https://github.com/user-attachments/assets/2512b173-b121-46b3-bf6a-9f7e921415b5)

In Linux sound settings, however I can't see it as input device.
![image](https://github.com/user-attachments/assets/91e9726d-44ee-447b-9f19-8ca74c427270)

In PulseAudio Input Devices shows this by default.
![image](https://github.com/user-attachments/assets/3de8d02f-2032-4655-bd37-0c6de7d4d057)

When I change "Show" to "All Input Devices" it shows "Monitor of Broo".
![image](https://github.com/user-attachments/assets/a5263c9f-d9d7-491b-ab88-7099c7cf484c)

**Comment by siddhpant** [comment]
Can you take a look at #10? It seems to be the same problem.

Maybe we can move the convo there.

**Comment by siddhpant** [comment]
Sorry, dumb me changed a part of the code was commonly used.

This specific problem should be fixed now.

Thanks for reporting!

**Comment by siddhpant** [comment]
No, this was fixed.

Also that exact line doesn't exist (the source calls a function instead), so you modified something.

Use `set -e` at the top of script to see where it fails if you are having an issue, and open a new issue if you think its an issue with Broo.

Your "fork" removed all the git history and changed source. Why?
