### ISSUE TITLE
lossless codec

### ISSUE THREAD

**Issue by hitanol** [siddhpant/broo#3]
Any workaround or alternativa to stream a lossless audio? I was looking for this [thread](https://unix.stackexchange.com/questions/116919/redirect-sound-microphone-via-ssh-how-to-telephone-via-ssh)  but don't know if it is easy to do

**Comment by siddhpant** [comment]
The mentioned way shouldn't be hard to do. `ffmpeg` saves your mic input to a file, what the command is doing is just sending it over ssh to another computer where you hear it or save it. After some trial and error while setting up, you can use it easily. Basically it is `mic -> ffmpeg -> output -> piped over ssh`. Latency may be noticeable. You can probably also use VLC to stream over network.

Though, Broo's mumble configuration is already set to using [510 kbps](https://github.com/siddhpant/broo/blob/main/setup_broo#L253). Mumble uses OPUS which has nice quality. Use the same settings on other side too.

I am not sure why would you need lossless mic when the quality is good enough already with low latency.

**Comment by hitanol** [comment]
hey, and, im having a problem with the broo's source, i cant link it to easyeffects input and apply fx to the virtual mic, theres no monitor of broo in helvum or pavucontrol to make a manual link :/
