### ISSUE TITLE
Monitor of Broo not showing up

### ISSUE THREAD

**Issue by siddhpant** [siddhpant/broo#4]
hey, and, im having a problem with the broo's source, i cant link it to easyeffects input and apply fx to the virtual mic, theres no monitor of broo in helvum or pavucontrol to make a manual link :/

_Originally posted by @hitanol in https://github.com/siddhpant/broo/issues/3#issuecomment-1052125280_

**Comment by siddhpant** [comment]
@hitanol Does Broo work normally? Can you use it as a mic in applications?

Also note that sink's name is `Broo`, not `Monitor of Broo`, that's just the Monitor's name shown on GUI.

**Comment by hitanol** [comment]
yes, i can in some apps
![image](https://user-images.githubusercontent.com/99027279/155852034-5603c275-40c3-4c2b-aec1-1ea15b93b288.png)

in case of obs it doesnt appear in mic section too
https://stream.bunkr.is/v/doc_2022-02-26_12-07-48-FuKHH5XH.mp4

**Comment by siddhpant** [comment]
This is not an issue with Broo but with OBS, since it detects it but doesn't show it.

In fact, the video shows Broo as an option for desktop audio (I don't know Spanish, so I'm guessing it based on [an older script's README](https://github.com/pzmarzly/mic_over_mumble), which will probably serve as a mic.

**Comment by hitanol** [comment]
i think, its shown in the monitoring devices
![image](https://user-images.githubusercontent.com/99027279/155854630-70605d09-dd99-4d09-ac31-e544bcf43458.png)

**Comment by siddhpant** [comment]
I guess that suffices. I don't use OBS either way, and the problem if any is on its end.
